CREATE
SEQUENCE IF NOT EXISTS todo_seq START
WITH 1 INCREMENT BY 50;

CREATE
SEQUENCE IF NOT EXISTS users_seq START
WITH 1 INCREMENT BY 50;

CREATE TABLE task
(
    tid         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    priority    VARCHAR(255),
    CONSTRAINT pk_task PRIMARY KEY (tid)
);

CREATE TABLE todo
(
    id   INTEGER NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_todo PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       INTEGER NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    email    VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);